# @format

name: aoc
version: 0.1.0.1
github: 'chrisnorris/aoc'
license: BSD3
author: 'Christopher Norris'
maintainer: 'me'
copyright: '2021 Christopher Norris'

extra-source-files:
    - README.md
    - ChangeLog.md

default-extensions:
    - BangPatterns
    - DeriveFunctor
    - DuplicateRecordFields
    - FlexibleContexts
    - FlexibleInstances
    - GADTs
    - GeneralizedNewtypeDeriving
    - ImportQualifiedPost
    - InstanceSigs
    - LambdaCase
    - MultiParamTypeClasses
    - MultiWayIf
    - NamedFieldPuns
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - UndecidableInstances
    - ViewPatterns

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/chrisnorris/aoc#readme>

dependencies:
    - array
    - base >= 4.7 && < 5
    - comonad
    - data-clist
    - filepath
    - lens
    - parsec
    - regex-tdfa
    - containers
    - transformers
    - criterion
    - clock
    - extra
    - vector
    - split
    - text
    - mtl
    - List
    - ListTree
    - monad-par
    - parallel
library:
    source-dirs: src

executables:
    aoc-exe:
        main: main.hs
        source-dirs: app
        ghc-options:
            - -O3
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N8
            - -with-rtsopts=-H128G
            - -with-rtsopts=-K2G
        dependencies:
            - aoc
